DATA_TYPES = {
    "STARTTIME":    str,
    "HOSTNAME":     str,
    "DATE":         str,
    "RELEASE":      str, 
    "CABLE":        str,
    "MODEL":        str,
    "UPSMODE":      str, 
    "UPSNAME":      str,
    "LINEV":        float, 
    "MAXLINEV":     float, 
    "MINLIVEV":     float, 
    "LINEFREQ":     float, 
    "OUTPUTV":      float, 
    "LOADPCT":      float, 
    "BATTV":        float, 
    "BCHARGE":      float, 
    "MBATTCHG":     int, 
    "TIMELEFT":     float, 
    "MINTIMEL":     int, 
    "SENSE":        str, 
    "DWAKE":        int, 
    "DSHUTD":       int, 
    "LOTRANS":      float, 
    "HITRANS":      float, 
    "RETPCT":       float, 
    "STATFLAG":     str, 
    "STATUS":       str, 
    "ITEMP":        float, 
    "ALARMDEL":     str, 
    "LASTXFER":     str, 
    "SELFTEST":     str, 
    "STESTI":       int, 
    "DLOWBATT":     int, 
    "DIPSW":        str, 
    "REG1":         str, 
    "REG2":         str, 
    "REG3":         str, 
    "MANDATE":      str, 
    "SERIALNO":     str,
    "BATTDATE":     str, 
    "NOMOUTV":      float, 
    "NOMBATTV":     float, 
    "NOMPOWER":     int, 
    "EXTBATTS":     int, 
    "FIRMWARE":     str, 
    "APCMODEL":     str,
    "CUMONBAT":     int, 
    "END APC":      str
}

REMOVE_KEYS = [
    "DATE",
    "STARTTIME",
    "CABLE",
    "END APC"
]

TAG_KEYS = [
    "HOSTNAME",
    "MODEL",
    "UPSNAME",
    "SERIALNO"
]
